# Generated by Django 4.2.7 on 2023-11-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rateings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
